### ISSUE TITLE
Possibility of adding a --verbose option?

### ISSUE THREAD

**Issue by jasonmerino** [tarunc/gulp-jsbeautifier#10]
The logging of every file that gets beautified gets a little noisy in the terminal when you're running this against a few hundred files. I think adding an option to make it verbose would be nice for users who don't want as much information coming through.

I'd be happy to submit a pull request for it if you think it's a good idea.

If this seems like a "breaking" change a `--silent` option would be just as helpful. Thanks!

**Comment by tarunc** [comment]
You can already pass in a [`logSuccess`](https://github.com/tarunc/gulp-jsbeautifier#optionslogsuccess-optional) option. By default, it is set to true but if you change it to false, it should not print out files that are beautified. 

For example:
```
gulp.task('format-js', function() {
  gulp.src(['./src/foo.js', './src/bar.json'])
    .pipe(prettify({config: '.jsbeautifyrc', mode: 'VERIFY_AND_WRITE', logSuccess: false}))
    .pipe(gulp.dest('./build'));
});
```

**Comment by jasonmerino** [comment]
Ahhhh! That's what `logSuccess` is for. Thanks! That fixed it up. :)
