### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by keradus** [tarunc/gulp-jsbeautifier#11]
Hi!
Is it a stable and maintained package?
If yes - could you be so kind and release v1.0.0 ?

**Comment by tarunc** [comment]
Yes it is. I have released [v1.0.0](https://github.com/tarunc/gulp-jsbeautifier/releases/tag/v1.0.0) onto [npm](https://www.npmjs.com/package/gulp-jsbeautifier).

**Comment by keradus** [comment]
Great to hear that! Thank you
