### ISSUE TITLE
VERIFY_ONLY without diff

### ISSUE THREAD

**Issue by keradus** [tarunc/gulp-jsbeautifier#13]
Hi, is it possible to run plugin with `VERIFY_ONLY` option but without printing diff of file? I would be extra happy to just report file name. Perhaps this would need extra option?

**Comment by tarunc** [comment]
There is a [`showDiff`](https://github.com/tarunc/gulp-jsbeautifier#optionsshowdiff-optional) option.

It can be used as such:
```js
gulp.task('git-pre-js', function() {
  gulp.src('./src/foo.js', './src/bar.json')
    .pipe(prettify({config: '.jsbeautifyrc', mode: 'VERIFY_ONLY', showDiff: false}))
});
```

**Comment by keradus** [comment]
OK, it was a missing option for gulp plugin.
Added 2 days ago (ref https://github.com/tarunc/gulp-jsbeautifier/commit/234d60c31f66a82b579d0516c61da844aa26547d)
Thank you!
