### ISSUE TITLE
"File type not specified for <any file>"

### ISSUE THREAD

**Issue by royts** [tarunc/gulp-jsbeautifier#23]
I'm trying to use `gulp-jsbeautifier` to beautify some .js files.

I don't see any change in files, and when using reporter I'm getting the error: `File type not specified for ...` for all files.

Looking into the code, I wrote the value of `file.basename` to console in the plugin code (`index.html`) right before checking what type is in (line 127: `_.endsWith(file.basename, ext);`.

I see that `file.basename` is `undefined`.

Any idea why?

---
some info:
module version: 2.0.0
os: osx

**Comment by tarunc** [comment]
Hey @royts, I published a major update (v2.0.0) to the package yesterday but looks like I might have introduced a bug inadvertently.

Thus, I'm removing gulp-jsbeautifier v2.0.0 from npm-- and will look into the bug tonight/try to push out an update. Please try running `npm i gulp-jsbeautifier@1.0.2` or `npm update` and try running your gulp task.

**Comment by royts** [comment]
@tarunc  - thank you. I downgraded to 1.0.2 and move to the old API, and it is working fine.
I'll be happy to help the fix. LMK.
Closing this.

**Comment by biasso** [comment]
I found the issue.
Try replace `_.endsWith(file.basename, ext);` with `return _.endsWith(path.basename(file.path), ext);`.

I fix other things and then public the new version.
