### ISSUE TITLE
How to beautify only non-beautified files

### ISSUE THREAD

**Issue by dhaval85** [tarunc/gulp-jsbeautifier#24]
Hello All, 

Every time I run the beautification it modifies and replace all the files. And it shows all the files in diff in IBM Jazz. However I only need non-beautified files to be beautified. Is there any option I can set?

Thanks,
D.

**Comment by biasso** [comment]
Hello @dhaval85

The default behavior is to beautify only non-beautified files.
Maybe you have some settings in your IDE contrasting those of gulp-jsbeautifier, e.g. tab instead of spaces.

If the output is correct (files are beautified), you can do a test using gulp-changed to see if anything changes.

Sorry but I don't know what it depends on.

**Comment by dhaval85** [comment]
The problem is whenever I run gulp beautify, every time it shows me all files modified. And I don't use IDE when I fire the gulp command. Therefore I believe the gulp beautify modifies files even though they are already beautified.

Regards, 
D.

**Comment by biasso** [comment]
Ok, so give me some more details to try to reproduce the issue:
- gulp version
- gulp-jsbeautifier version
- the gulp task with gulp-jsbeautifier
- the console output with the reporter and the gulp-jsbeautifier debug option setted to true

**Comment by dhaval85** [comment]
Hello @biasso 

Gulp Version: 3.9.1
Gulp JS Beautifier Version: 2.0.3

Gulp Task

`gulp.task('beautify',[],function(){
	gulp.src(['WebContent/**/*.js','WebContent/**/*.css','WebContent/**/*.html'])
	.pipe(prettify({
		indent_char: '\t',
    indent_size: 1,
		debug: true
	}))
	.pipe(gulp.dest('WebContent/'));
});`

Output: 
`[12:21:21] Starting 'beautify'...
[12:21:21] Configuration used:
{
  "config": null,
  "debug": true,
  "css": {
    "file_types": [
      ".css",
      ".less",
      ".sass",
      ".scss"
    ],
    "indent_char": "\t",
    "indent_size": 1
  },
  "html": {
    "file_types": [
      ".html"
    ],
    "indent_char": "\t",
    "indent_size": 1
  },
  "js": {
    "file_types": [
      ".js",
      ".json"
    ],
    "indent_char": "\t",
    "indent_size": 1
  }
}
[12:21:21] Finished 'beautify' after 65 ms`

**Comment by dhaval85** [comment]
Don't know why it's messed up although it's pasted within code block. Sorry about that.

**Comment by biasso** [comment]
I did some tests and everything works properly.
Gulp-jsbeautifier beautifies files only the first time.
The next times the reporter informs that the files are already beautified and `git diff` shows no changes.

**Comment by dhaval85** [comment]
Hmm. Now confused. May be IBM Jazz is some how not able to figure out the difference I guess. Have to look into this. Thank you @biasso

**Comment by dhaval85** [comment]
It's worked after I've added below options. 

end_with_newline:true,
eol: '\r\n'
