### ISSUE TITLE
How to make plugin start each tag from new line?

### ISSUE THREAD

**Issue by syampolskiy** [tarunc/gulp-jsbeautifier#28]
I don't think that this is prettifying
`<div id="social_media_wrapper"><a class="social-link--fb" href="https://www.facebook.com/mymailingroom"><i class="fa fa-facebook"><span>&nbsp;</span></i></a><a class="social-link--tw" href="https://twitter.com/mymailingroom"><i class="fa fa-twitter"><span>&nbsp;</span></i></a>
				<a
				class="social-link--g" href="http://google.com/+MyMailingRoomGreenhithe"><i class="fa fa-google-plus"><span>&nbsp;</span></i>
					</a><a class="social-link--in" href="https://www.linkedin.com/company/my-mailing-room"><i class="fa fa-linkedin"><span>&nbsp;</span></i></a>
			</div>`

Which options should I use to start EACH (all, everything, etc...) tag from new line?

**Comment by biasso** [comment]
```
gulp.task('beautify-html', () =>
  gulp.src("./src/*.html")
  .pipe(prettify({
    html: {
      unformatted: []
    }
  }))
  .pipe(prettify.reporter())
  .pipe(gulp.dest('./dist'))
);
```
