### ISSUE TITLE
Unable to specify replace

### ISSUE THREAD

**Issue by jasonmerino** [tarunc/gulp-jsbeautifier#9]
Maybe I'm missing something here, and I totally could be, but I can't figure out how to pass the replace option to jsbeautifier here. I'm using `grunt-jsbeautifier` to beautify source files in my current project. We want to switch over to using gulp, but with this gulp plugin I'm not finding a way to do that well.

Any help with this would be much appreciated.

**Comment by tarunc** [comment]
I don't know what `replace` option you are talking about. It would be helpful to include the code that you are trying to debug and get working. 

In general, this module was created as a replacement to `grunt-jsbeautifier` so you should be able to do all the things with this module that you can do with `grunt-jsbeautifier`.

If you are looking to automatically beautify files, you can use the `mode` option. Just set it to, `VERIFY_AND_WRITE`, like this:
```js
gulp.task('format-js', function() {
  gulp.src('./src/foo.js', './src/bar.json') // <- the input files
    .pipe(prettify({config: '.jsbeautifyrc', mode: 'VERIFY_AND_WRITE'})) // <- prettify = require('gulp-jsbeautifier');
    .pipe(gulp.dest('./dist')) // <- the folder in which to write the files
});
```

If you are looking to pass options to the [`jsbeautifier`](https://github.com/beautify-web/js-beautify), you can either pass them in using a `.jsbeautifyrc` file or as options in gulp. (included below)
```js
gulp.task('prettify-css', function() {
  gulp.src('./src/foo.css')
    .pipe(prettify({indent_size: 2}))
    .pipe(gulp.dest('./build'));
});
```

The `replace` command-line option in  [`jsbeautifier`](https://github.com/beautify-web/js-beautify) is to output files and you can do that with gulp by specifying a destination directory and using the `{ mode: 'VERIFY_AND_WRITE' }`.

**Comment by jasonmerino** [comment]
Okay, I got it figured out. I wanted to replace the source files with the formatted versions of themselves. Here's what I came up with:

```javascript
return gulp
	.src(['app/**/*.js'], {
		base: './'
	})
	.pipe(cache('jsbeautify'))
	.pipe(beautify({
		indentSize: 1,
		indentChar: '\t'
	}))
	.pipe(gulp.dest('./'));
```

The `base` property for the glob and the `dest` path needed to match. This seems to do the same thing as if I were to add the `{ mode: 'VERIFY_AND_WRITE' } `.
